### ISSUE TITLE
Fix sizing & styling of the top bar elements

### ISSUE THREAD

**Issue by bmorrisondev** [bmorrisondev/apostle#6]
- The method dropdown should be spaced more appropriately. Something like 200-300px;
- The API Endpoint Address should take up the remaining space.
- The placeholders should not drift above the app view when clicked on.

![image](https://user-images.githubusercontent.com/4684030/66439918-e4b7fb00-e9f6-11e9-8026-4ea723843d49.png)

**Comment by abdulamite** [comment]
This issue should now be resolved since removing vuetify and my most recent PR to clean up address bar styles.
