### ISSUE TITLE
Fix margins in app based on breakpoint

### ISSUE THREAD

**Issue by bmorrisondev** [bmorrisondev/apostle#9]
There seems to be some margin on the right before various breakpoints, like the grid is not fully expanding after a certain width;

![image](https://user-images.githubusercontent.com/4684030/66441321-f5b73b00-e9fb-11e9-8edd-f9a36aeb8cfe.png)

**Comment by abdulamite** [comment]
I am unable to reproduce this issue on Mac (v.10.14.6). Is this something that is still occurring after removing vuetify? If this is something you are still seeing, we can just wrap the `grid-left` and `grid-right` in a parent div, and set the width of this new element to 100%.

**Comment by bmorrisondev** [comment]
Was an issue until Vuetify was removed. Been resolved since. Thanks.
